redisson:
  address: redis://192.168.1.106:6379
  password: web2017



spring:
  application:
    name: common-redis
  redis:
    database: 1
    host: 192.168.1.106
    port: 6379
    jedis:
      pool:
        max-active: 200 #最大连接数
        max-wait: -1 #连接池最大等待时间(负数表示没有限制)
        max-idle: 10 #连接池最大空闲数
        min-idle: 0 #连接池最小空闲数
    timeout: 2000
server:
  port: 9080

#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://eureka-server:8761/eureka/
